mutation Invite($input: InviteTeammateInput!) {
  InviteTeammate(input: $input) {
    teammates {
      email
      role
    }
    invites {
      id
      email
      role
      signedUp
    }
  }
}
