import { builder } from '@/server/api/graphql/builder'

import '@/server/api/graphql/models/User'
import '@/server/api/graphql/models/apiKeys'
import '@/server/api/graphql/models/contracts'
import '@/server/api/graphql/models/explorerVerificiations'
import '@/server/api/graphql/models/invites/index'
import '@/server/api/graphql/models/multichainDeployments'
import '@/server/api/graphql/models/multichainDeployments/mutations/addSignature'
import '@/server/api/graphql/models/multichainDeployments/mutations/cancel'
import '@/server/api/graphql/models/networks'
import '@/server/api/graphql/models/organizations'
import '@/server/api/graphql/models/organizations/mutations/inviteTeammate'
import '@/server/api/graphql/models/organizations/mutations/updateTeammate'
import '@/server/api/graphql/models/projectDeployments'
import '@/server/api/graphql/models/projectNetworks'
import '@/server/api/graphql/models/projectVerifications'
import '@/server/api/graphql/models/projects'
import '@/server/api/graphql/models/projects/mutations/createProject'
import '@/server/api/graphql/models/projects/mutations/updateProject'
import '@/server/api/graphql/models/safeDeploymentStrategy'
import '@/server/api/graphql/models/safeOwners'
import '@/server/api/graphql/models/treeChainStatus'
import '@/server/api/graphql/models/treeSigners'
import '@/server/api/graphql/scalars'

export const schema = builder.toSchema({})
