name: Build and Publish Docker Images

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: [artifact-generator, contract-verifier, executor, relayer, init]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - name: Build Service Sources
      run: yarn build:services

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image }}:latest
        file: ./services/${{ matrix.image }}/Dockerfile

    - name: Logout from DockerHub
      run: docker logout
